project:
  type: website
  output-dir: docs

website:
  title: "Joey Cahill - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: weekly-notes/
        text: Weekly Notes
      - text: Labs
        menu:
          - href: weekly-notes/week-01-notes.qmd
            text: Week 1
          - href: labs/lab_0/
            text: "Lab 0: dplyr Basics"
          - href: labs/lab_1/
            text: "Lab 1: Assignment 1"
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto