{
  "hash": "d4d44493c9e8d808536232bd33b5995a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 1: Census Data Quality for Policy Decisions\"\nsubtitle: \"Evaluating Data Reliability for Algorithmic Decision-Making\"\nauthor: \"Joey Cahill\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\nexecute:\n  warning: false\n  message: false\n---\n\n# Assignment Overview\n\n## Scenario\n\nYou are a data analyst for the **PA Department of Human Services**. The department is considering implementing an algorithmic system to identify communities that should receive priority for social service funding and outreach programs. Your supervisor has asked you to evaluate the quality and reliability of available census data to inform this decision.\n\nDrawing on our Week 2 discussion of algorithmic bias, you need to assess not just what the data shows, but how reliable it is and what communities might be affected by data quality issues.\n\n## Learning Objectives\n\n- Apply dplyr functions to real census data for policy analysis\n- Evaluate data quality using margins of error \n- Connect technical analysis to algorithmic decision-making\n- Identify potential equity implications of data reliability issues\n- Create professional documentation for policy stakeholders\n\n## Submission Instructions\n\n**Submit by posting your updated portfolio link on Canvas.** Your assignment should be accessible at `your-portfolio-url/assignments/assignment_1/`\n\nMake sure to update your `_quarto.yml` navigation to include this assignment under an \"Assignments\" menu.\n\n# Part 1: Portfolio Integration\n\nCreate this assignment in your portfolio repository under an `assignments/assignment_1/` folder structure. Update your navigation menu to include:\n\n```\n- text: Assignments\n  menu:\n    - href: assignments/assignment_1/your_file_name.qmd\n      text: \"Assignment 1: Census Data Exploration\"\n```\nIf there is a special character like comma, you need use double quote mark so that the quarto can identify this as text\n\n# Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidycensus)\nlibrary(tidyverse)\nlibrary(knitr)\ncensus_api_key(\"8deb926015351433bef092c55a5e8a90573283bd\")\n```\n:::\n\n# Choose your state for analysis - assign it to a variable called my_state\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"Pennsylvania\"\n```\n:::\n\n\nState Selection: I have chosen **Pennsylvania** for this analysis because: I am from PA originally and currently reside and vote in it. The issues I will explore in this analysis will be directly relevant to my community.\n\n# Part 2: County-Level Resource Assessment\n\n## 2.1 Data Retrieval\n\n**Your Task:** Use `get_acs()` to retrieve county-level data for your chosen state.\n\n**Requirements:**\n- Geography: county level\n- Variables: median household income (B19013_001) and total population (B01003_001)  \n- Year: 2022\n- Survey: acs5\n- Output format: wide\n\n**Hint:** Remember to give your variables descriptive names using the `variables = c(name = \"code\")` syntax.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your get_acs() code here\n\npa_county_data <- get_acs(\n  geography = \"county\",\n  variables = c(median_income = \"B19013_001\", total_population = \"B01003_001\"),\n  state = my_state,\n  year = 2022,\n  survey = \"acs5\",\n  output = \"wide\")\n# Clean the county names to remove state name and \"County\" \n# Hint: use mutate() with str_remove()\npa_clean <- pa_county_data %>%\n  mutate(\n    county_name = str_remove(NAME, \", Pennsylvania\"),\n    county_name = str_remove(county_name, \" County\"))\n# Display the first few rows\nhead(pa_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  GEOID NAME   median_incomeE median_incomeM total_populationE total_populationM\n  <chr> <chr>           <dbl>          <dbl>             <dbl>             <dbl>\n1 42001 Adams…          78975           3334            104604                NA\n2 42003 Alleg…          72537            869           1245310                NA\n3 42005 Armst…          61011           2202             65538                NA\n4 42007 Beave…          67194           1531            167629                NA\n5 42009 Bedfo…          58337           2606             47613                NA\n6 42011 Berks…          74617           1191            428483                NA\n# ℹ 1 more variable: county_name <chr>\n```\n\n\n:::\n:::\n\n\n## 2.2 Data Quality Assessment\n\n**Your Task:** Calculate margin of error percentages and create reliability categories.\n\n**Requirements:**\n- Calculate MOE percentage: (margin of error / estimate) * 100\n- Create reliability categories:\n  - High Confidence: MOE < 5%\n  - Moderate Confidence: MOE 5-10%  \n  - Low Confidence: MOE > 10%\n- Create a flag for unreliable estimates (MOE > 10%)\n\n**Hint:** Use `mutate()` with `case_when()` for the categories.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate MOE percentage and reliability categories using mutate()\n\n\npa_reliability <- pa_clean %>%\n  mutate(\n    # Calculate MOE as percentage of estimate\n    moe_percentage = round((median_incomeM / median_incomeE) * 100, 2),\n    \n    # Create reliability categories\n    reliability = case_when(\n      moe_percentage < 5 ~ \"High Confidence\",\n      moe_percentage >= 5 & moe_percentage <= 10 ~ \"Moderate\",\n      moe_percentage > 10 ~ \"Low Confidence\"\n    )\n  )\n\ncount(pa_reliability, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  reliability         n\n  <chr>           <int>\n1 High Confidence    57\n2 Moderate           10\n```\n\n\n:::\n\n```{.r .cell-code}\n# Create a summary showing count of counties in each reliability category\n# Hint: use count() and mutate() to add percentages\n```\n:::\n\n\n## 2.3 High Uncertainty Counties\n\n**Your Task:** Identify the 5 counties with the highest MOE percentages.\n\n**Requirements:**\n- Sort by MOE percentage (highest first)\n- Select the top 5 counties\n- Display: county name, median income, margin of error, MOE percentage, reliability category\n- Format as a professional table using `kable()`\n\n**Hint:** Use `arrange()`, `slice()`, and `select()` functions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create table of top 5 counties by MOE percentage\nhigh_uncertainty <- pa_reliability %>%\n  arrange(desc(moe_percentage)) %>%\n  slice_head(n = 5) %>%\n  select(county_name, median_incomeE, median_incomeM,total_populationE, moe_percentage, reliability)\n\n# Format as table with kable()\nkable(\n  high_uncertainty,\n  col.names = c(\"County\", \"Median Income\",\"Total Population\", \"Margin of Error\", \"MOE %\", \"Reliability\"),\n  caption = \"Top 5 Pennsylvania Counties by Income Data Uncertainty\",\n  format.args = list(big.mark = \",\")\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 5 Pennsylvania Counties by Income Data Uncertainty\n\n|County   | Median Income| Total Population| Margin of Error| MOE %|Reliability |\n|:--------|-------------:|----------------:|---------------:|-----:|:-----------|\n|Forest   |        46,188|            4,612|           6,959|  9.99|Moderate    |\n|Sullivan |        62,910|            5,821|           5,880|  9.25|Moderate    |\n|Union    |        64,914|            4,753|          42,908|  7.32|Moderate    |\n|Montour  |        72,626|            5,146|          18,165|  7.09|Moderate    |\n|Elk      |        61,672|            4,091|          30,886|  6.63|Moderate    |\n\n\n:::\n:::\n\n\n**Data Quality Commentary:**\n\n[Write 2-3 sentences explaining what these results mean for algorithmic decision-making. Consider: Which counties might be poorly served by algorithms that rely on this income data? What factors might contribute to higher uncertainty?]\n\nIf these counties are served by algorithmic decision making based on census data, they are vulnerable to bias and misrepresentation of their populations risking misappropriation of resources. The above Counties have the top 5 margin's of error within the dataset and very small populations.These are rural counties that are highly likely to need social assistance and state funding due to their lack of municipal resources. Their recorded median incomes are at risk of being misrepresented by a sample population that is more likely to have access to internet and more likely for their incomes to be on record. Poor rural communities tend to be underrepresented in census data due to their remoteness and lack of  \n\n# Part 3: Neighborhood-Level Analysis\n\n## 3.1 Focus Area Selection\n\n**Your Task:** Select 2-3 counties from your reliability analysis for detailed tract-level study.\n\n**Strategy:** Choose counties that represent different reliability levels (e.g., 1 high confidence, 1 moderate, 1 low confidence) to compare how data quality varies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use filter() to select 2-3 counties from your county_reliability data\n# Store the selected counties in a variable called selected_counties\n# Display the selected counties with their key characteristics\n# Show: county name, median income, MOE percentage, reliability category\n# Define the counties you want\nselected_county_names <- c(\"Delaware\", \"Montour\", \"Jefferson\")\n\nselected_counties <- pa_reliability %>%\n  filter(county_name %in% selected_county_names) %>%\n  select(county_name, median_incomeE,total_populationE, moe_percentage, reliability)\n\nkable(\n  selected_counties,\n  col.names = c(\"County\", \"Median Income\",\"Total Population\", \"MOE %\", \"Reliability\"),\n  caption = \"Selected Counties: Key Income Estimate Characteristics\",\n  format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\nTable: Selected Counties: Key Income Estimate Characteristics\n\n|County    | Median Income| Total Population| MOE %|Reliability     |\n|:---------|-------------:|----------------:|-----:|:---------------|\n|Delaware  |        86,390|          575,312|  1.53|High Confidence |\n|Jefferson |        56,607|           44,326|  3.41|High Confidence |\n|Montour   |        72,626|           18,165|  7.09|Moderate        |\n\n\n:::\n:::\n\n\n**Comment on the output:** I selected counties from three areas of the Reliability spectrum for comparison. A general trend seems to be that with higher population comes lower margin of error. These high population areas would see less errors from algorithm based service on their behalf. Conversely, potential error in lower population area's should be compensated for via more enhanced predictive modeling or simply a need based increase in service. A request based funding allotment could be a good stop gap until more accurate information is availible.\n\n## 3.2 Tract-Level Demographics\n\n**Your Task:** Get demographic data for census tracts in your selected counties.\n\n**Requirements:**\n- Geography: tract level\n- Variables: white alone (B03002_003), Black/African American (B03002_004), Hispanic/Latino (B03002_012), total population (B03002_001)\n- Use the same state and year as before\n- Output format: wide\n- **Challenge:** You'll need county codes, not names. Look at the GEOID patterns in your county data for hints.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define your race/ethnicity variables with descriptive names\nrace_vars <- c(\n  white = \"B03002_003\",\n  black = \"B03002_004\",\n  hispanic = \"B03002_012\",\n  total_pop = \"B03002_001\"\n)\n# Use get_acs() to retrieve tract-level data\n# Hint: You may need to specify county codes in the county parameter\n\ntract_demo <- get_acs(\n  geography = \"tract\",\n  variables = race_vars,\n  state = my_state,\n  county = c(\"045\", \"065\", \"093\"),  # can use names or FIPS codes\n  year = 2022,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\n# Calculate percentage of each group using mutate()\n\ntract_demo <- tract_demo %>%\n  mutate(\n    pct_white = round((whiteE / total_popE) * 100, 1),\n    pct_black = round((blackE / total_popE) * 100, 1),\n    pct_hispanic = round((hispanicE / total_popE) * 100, 1)\n  )\n\n# Create percentages for white, Black, and Hispanic populations\n\n# Add readable tract and county name columns using str_extract() or similar\n\ntract_demo <- tract_demo %>%\n  separate(NAME, into = c(\"tract_name\", \"county_name\", \"state\"), sep = \"; \") %>%\n  select(-state)\n\nhead(tract_demo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 14\n  GEOID   tract_name county_name whiteE whiteM blackE blackM hispanicE hispanicM\n  <chr>   <chr>      <chr>        <dbl>  <dbl>  <dbl>  <dbl>     <dbl>     <dbl>\n1 420454… Census Tr… Delaware C…   1345    607   4112    637       794       474\n2 420454… Census Tr… Delaware C…    574    269   2206    450       384       215\n3 420454… Census Tr… Delaware C…    720    401   3205    685       965       464\n4 420454… Census Tr… Delaware C…    493    160   2745    490       548       256\n5 420454… Census Tr… Delaware C…   1120    346   1720    509       417       286\n6 420454… Census Tr… Delaware C…   2557    465   1502    803       625       443\n# ℹ 5 more variables: total_popE <dbl>, total_popM <dbl>, pct_white <dbl>,\n#   pct_black <dbl>, pct_hispanic <dbl>\n```\n\n\n:::\n:::\n\n\n## 3.3 Demographic Analysis\n\n**Your Task:** Analyze the demographic patterns in your selected areas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Find the tract with the highest percentage of Hispanic/Latino residents\n# Hint: use arrange() and slice() to get the top tract\ntop_hispanic_tract <- tract_demo %>%\n  arrange(desc(pct_hispanic)) %>%\n  slice(1)\n\ntop_hispanic_tract\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 14\n  GEOID   tract_name county_name whiteE whiteM blackE blackM hispanicE hispanicM\n  <chr>   <chr>      <chr>        <dbl>  <dbl>  <dbl>  <dbl>     <dbl>     <dbl>\n1 420454… Census Tr… Delaware C…   1256    441   1864    413      1266       534\n# ℹ 5 more variables: total_popE <dbl>, total_popM <dbl>, pct_white <dbl>,\n#   pct_black <dbl>, pct_hispanic <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate average demographics by county using group_by() and summarize()\n# Show: number of tracts, average percentage for each racial/ethnic group\n\ncounty_summary <- tract_demo %>%\n  group_by(county_name) %>%\n  summarize(\n    n_tracts = n(),\n    avg_pct_white = round(mean(pct_white, na.rm = TRUE), 1),\n    avg_pct_black = round(mean(pct_black, na.rm = TRUE), 1),\n    avg_pct_hispanic = round(mean(pct_hispanic, na.rm = TRUE), 1)\n  ) %>%\n  ungroup()\n\n# Create a nicely formatted table of your results using kable()\n\nkable(county_summary, caption = \"Average Demographics by County (ACS 2022 5-Year)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Average Demographics by County (ACS 2022 5-Year)\n\n|county_name      | n_tracts| avg_pct_white| avg_pct_black| avg_pct_hispanic|\n|:----------------|--------:|-------------:|-------------:|----------------:|\n|Delaware County  |      152|          62.4|          24.3|              4.2|\n|Jefferson County |       13|          95.9|           0.4|              1.2|\n|Montour County   |        4|          89.9|           2.3|              2.9|\n\n\n:::\n:::\n\n\n# Part 4: Comprehensive Data Quality Evaluation\n\n## 4.1 MOE Analysis for Demographic Variables\n\n**Your Task:** Examine margins of error for demographic variables to see if some communities have less reliable data.\n\n**Requirements:**\n- Calculate MOE percentages for each demographic variable\n- Flag tracts where any demographic variable has MOE > 15%\n- Create summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate MOE percentages for white, Black, and Hispanic variables\n# Hint: use the same formula as before (margin/estimate * 100)\n\ntract_moe <- tract_demo %>%\n  mutate(\n    moe_pct_white    = round((whiteM / whiteE) * 100, 1),\n    moe_pct_black    = round((blackM / blackE) * 100, 1),\n    moe_pct_hispanic = round((hispanicM / hispanicE) * 100, 1)\n  )\n\n# Create a flag for tracts with high MOE on any demographic variable\n\ntract_moe <- tract_moe %>%\n  mutate(\n    high_moe_flag = ifelse(\n      moe_pct_white > 50 | moe_pct_black > 50 | moe_pct_hispanic > 50,\n      TRUE, FALSE\n    )\n  )\n\n# Use logical operators (| for OR) in an ifelse() statement\n\n# Create summary statistics showing how many tracts have data quality issues\nmoe_summary <- tract_moe %>%\n  summarize(\n    total_tracts = n(),\n    tracts_with_high_moe = sum(high_moe_flag, na.rm = TRUE),\n    pct_with_high_moe = round((tracts_with_high_moe / total_tracts) * 100, 1)\n  )\n\nmoe_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  total_tracts tracts_with_high_moe pct_with_high_moe\n         <int>                <int>             <dbl>\n1          169                  161              95.3\n```\n\n\n:::\n:::\n\n\n## 4.2 Pattern Analysis\n\n**Your Task:** Investigate whether data quality problems are randomly distributed or concentrated in certain types of communities.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Group tracts by whether they have high MOE issues\n# Calculate average characteristics for each group:\n# - population size, demographic percentages\n\npattern_summary <- tract_moe %>%\n  group_by(high_moe_flag) %>%\n  summarize(\n    n_tracts       = n(),\n    avg_pop        = round(mean(total_popE, na.rm = TRUE), 0),\n    avg_pct_white  = round(mean(pct_white, na.rm = TRUE), 1),\n    avg_pct_black  = round(mean(pct_black, na.rm = TRUE), 1),\n    avg_pct_hisp   = round(mean(pct_hispanic, na.rm = TRUE), 1)\n  )\n\n# Use group_by() and summarize() to create this comparison\n# Create a professional table showing the patterns\nkable(\n  pattern_summary,\n  col.names = c(\n    \"High MOE Flag\",\n    \"Number of Tracts\",\n    \"Avg Population\",\n    \"Avg % White\",\n    \"Avg % Black\",\n    \"Avg % Hispanic\"\n  ),\n  caption = \"Comparison of Tracts by Data Reliability (MOE > 50%)\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Comparison of Tracts by Data Reliability (MOE > 50%)\n\n|High MOE Flag | Number of Tracts| Avg Population| Avg % White| Avg % Black| Avg % Hispanic|\n|:-------------|----------------:|--------------:|-----------:|-----------:|--------------:|\n|FALSE         |                8|           5429|        47.4|        28.7|            9.6|\n|TRUE          |              161|           3692|        66.6|        21.5|            3.6|\n\n\n:::\n:::\n\n\n**Pattern Analysis:** I observe no pattern with a high MOE cutoff score of 15% (All tracts met this criteria). Raising the threshold to 50% MOE, 95.3% of tracts still qualified as High Margin of Error Tracts. A lower average population of 3,692 v. 5,429 in the High MOE Tracts under the new criteria indicates that lower population tracts are more at risk for data quality issues. An increase from 47.4% to 66.6% White Population in these high risk tracts also indicates that the tracts with lower populations tend to be predominantly White demographically.\n\n# Part 5: Policy Recommendations\n\n## 5.1 Analysis Integration and Professional Summary\n\n**Your Task:** Write an executive summary that integrates findings from all four analyses.\n\n**Executive Summary Requirements:**\n1. **Overall Pattern Identification**: What are the systematic patterns across all your analyses?\n\nThe chief systematic pattern across all my analysis was the inverse relationship between population and margin of error. Both counties and tracts that contained lower populations were more likely to have higher margins of error.\n\n2. **Equity Assessment**: Which communities face the greatest risk of algorithmic bias based on your findings?\n\nThis analysis showed that these rural communities face the largest risk of misrepresentation when employing algorithmic decision making. I would like to increase the scope of the study to examine urban population in more detail to understand which demographics are at higher risk of misrepresentation regardless of population dsensity. \n\n3. **Root Cause Analysis**: What underlying factors drive both data quality issues and bias risk?\n\nSystemic factors like poverty, historical oppression, and political and economic conditions all contribute to bias within data sets. Any analysis based on census data must account for these factors or they risk harming underrepresented communities. Under reporting or over reporting of information is cause for inaccuracy in algorithmic decision making.\n\n4. **Strategic Recommendations**: What should the Department implement to address these systematic issues?\n\nThe department should include additional data in its analysis to create a more informed view of their target areas. Special attention should be payed to counties and tracts with a high Margin of Error in Census data. They should also allow for increased allocation of funds to these areas on an as needed basis. I would recommend a hybrid approach of algorithmic decision making and field research to determine resource allocation.\n\n\n\n**Executive Summary:**\n\nThe chief systematic pattern across all my analysis was the inverse relationship between population and margin of error. Both counties and tracts that contained lower populations were more likely to have higher margins of error.\n\nThis analysis showed that these rural communities face the largest risk of misrepresentation when employing algorithmic decision making. I would like to increase the scope of the study to examine urban population in more detail to understand which demographics are at higher risk of misrepresentation regardless of population dsensity.\n\nSystemic factors like poverty, historical oppression, and political and economic conditions all contribute to bias within data sets. Any analysis based on census data must account for these factors or they risk harming underrepresented communities. Under reporting or over reporting of information is cause for inaccuracy in algorithmic decision making.\n\nThe department should include additional data in its analysis to create a more informed view of their target areas. Special attention should be payed to counties and tracts with a high Margin of Error in Census data. They should also allow for increased allocation of funds to these areas on an as needed basis. I would recommend a hybrid approach of algorithmic decision making and field research to determine resource allocation.\n\n## 6.3 Specific Recommendations\n\n**Your Task:** Create a decision framework for algorithm implementation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a summary table using your county reliability data\n# Include: county name, median income, MOE percentage, reliability category\n# Add a new column with algorithm recommendations using case_when():\n# - High Confidence: \"Safe for algorithmic decisions\"\n# - Moderate Confidence: \"Use with caution - monitor outcomes\"  \n# - Low Confidence: \"Requires manual review or additional data\"\nrecommendations_table <- pa_reliability %>%\n  select(county_name, median_incomeE, moe_percentage, reliability) %>%\n  mutate(\n    algorithm_recommendation = case_when(\n      reliability == \"High Confidence\" ~ \"Safe for algorithmic decisions\",\n      reliability == \"Moderate\" ~ \"Use with caution - monitor outcomes\",\n      reliability == \"Low Confidence\" ~ \"Requires manual review or additional data\"))\n\n# Format as a professional table with kable()\n\nkable(\n  recommendations_table,\n  col.names = c(\"County\", \"Median Income\", \"MOE %\", \"Reliability\", \"Algorithm Recommendation\"),\n  caption = \"Algorithmic Decision-Making Recommendations by County\",\n  format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\nTable: Algorithmic Decision-Making Recommendations by County\n\n|County         | Median Income| MOE %|Reliability     |Algorithm Recommendation            |\n|:--------------|-------------:|-----:|:---------------|:-----------------------------------|\n|Adams          |        78,975|  4.22|High Confidence |Safe for algorithmic decisions      |\n|Allegheny      |        72,537|  1.20|High Confidence |Safe for algorithmic decisions      |\n|Armstrong      |        61,011|  3.61|High Confidence |Safe for algorithmic decisions      |\n|Beaver         |        67,194|  2.28|High Confidence |Safe for algorithmic decisions      |\n|Bedford        |        58,337|  4.47|High Confidence |Safe for algorithmic decisions      |\n|Berks          |        74,617|  1.60|High Confidence |Safe for algorithmic decisions      |\n|Blair          |        59,386|  3.47|High Confidence |Safe for algorithmic decisions      |\n|Bradford       |        60,650|  3.57|High Confidence |Safe for algorithmic decisions      |\n|Bucks          |       107,826|  1.41|High Confidence |Safe for algorithmic decisions      |\n|Butler         |        82,932|  2.61|High Confidence |Safe for algorithmic decisions      |\n|Cambria        |        54,221|  3.34|High Confidence |Safe for algorithmic decisions      |\n|Cameron        |        46,186|  5.64|Moderate        |Use with caution - monitor outcomes |\n|Carbon         |        64,538|  5.31|Moderate        |Use with caution - monitor outcomes |\n|Centre         |        70,087|  2.77|High Confidence |Safe for algorithmic decisions      |\n|Chester        |       118,574|  1.70|High Confidence |Safe for algorithmic decisions      |\n|Clarion        |        58,690|  4.37|High Confidence |Safe for algorithmic decisions      |\n|Clearfield     |        56,982|  2.79|High Confidence |Safe for algorithmic decisions      |\n|Clinton        |        59,011|  3.86|High Confidence |Safe for algorithmic decisions      |\n|Columbia       |        59,457|  3.76|High Confidence |Safe for algorithmic decisions      |\n|Crawford       |        58,734|  3.91|High Confidence |Safe for algorithmic decisions      |\n|Cumberland     |        82,849|  2.20|High Confidence |Safe for algorithmic decisions      |\n|Dauphin        |        71,046|  2.27|High Confidence |Safe for algorithmic decisions      |\n|Delaware       |        86,390|  1.53|High Confidence |Safe for algorithmic decisions      |\n|Elk            |        61,672|  6.63|Moderate        |Use with caution - monitor outcomes |\n|Erie           |        59,396|  2.55|High Confidence |Safe for algorithmic decisions      |\n|Fayette        |        55,579|  4.16|High Confidence |Safe for algorithmic decisions      |\n|Forest         |        46,188|  9.99|Moderate        |Use with caution - monitor outcomes |\n|Franklin       |        71,808|  3.00|High Confidence |Safe for algorithmic decisions      |\n|Fulton         |        63,153|  3.65|High Confidence |Safe for algorithmic decisions      |\n|Greene         |        66,283|  6.41|Moderate        |Use with caution - monitor outcomes |\n|Huntingdon     |        61,300|  4.72|High Confidence |Safe for algorithmic decisions      |\n|Indiana        |        57,170|  4.65|High Confidence |Safe for algorithmic decisions      |\n|Jefferson      |        56,607|  3.41|High Confidence |Safe for algorithmic decisions      |\n|Juniata        |        61,915|  4.79|High Confidence |Safe for algorithmic decisions      |\n|Lackawanna     |        63,739|  2.58|High Confidence |Safe for algorithmic decisions      |\n|Lancaster      |        81,458|  1.79|High Confidence |Safe for algorithmic decisions      |\n|Lawrence       |        57,585|  3.07|High Confidence |Safe for algorithmic decisions      |\n|Lebanon        |        72,532|  2.69|High Confidence |Safe for algorithmic decisions      |\n|Lehigh         |        74,973|  2.00|High Confidence |Safe for algorithmic decisions      |\n|Luzerne        |        60,836|  2.35|High Confidence |Safe for algorithmic decisions      |\n|Lycoming       |        63,437|  4.39|High Confidence |Safe for algorithmic decisions      |\n|McKean         |        57,861|  4.75|High Confidence |Safe for algorithmic decisions      |\n|Mercer         |        57,353|  3.63|High Confidence |Safe for algorithmic decisions      |\n|Mifflin        |        58,012|  3.43|High Confidence |Safe for algorithmic decisions      |\n|Monroe         |        80,656|  3.17|High Confidence |Safe for algorithmic decisions      |\n|Montgomery     |       107,441|  1.27|High Confidence |Safe for algorithmic decisions      |\n|Montour        |        72,626|  7.09|Moderate        |Use with caution - monitor outcomes |\n|Northampton    |        82,201|  1.93|High Confidence |Safe for algorithmic decisions      |\n|Northumberland |        55,952|  2.67|High Confidence |Safe for algorithmic decisions      |\n|Perry          |        76,103|  3.17|High Confidence |Safe for algorithmic decisions      |\n|Philadelphia   |        57,537|  1.38|High Confidence |Safe for algorithmic decisions      |\n|Pike           |        76,416|  4.90|High Confidence |Safe for algorithmic decisions      |\n|Potter         |        56,491|  4.42|High Confidence |Safe for algorithmic decisions      |\n|Schuylkill     |        63,574|  2.40|High Confidence |Safe for algorithmic decisions      |\n|Snyder         |        65,914|  5.56|Moderate        |Use with caution - monitor outcomes |\n|Somerset       |        57,357|  2.78|High Confidence |Safe for algorithmic decisions      |\n|Sullivan       |        62,910|  9.25|Moderate        |Use with caution - monitor outcomes |\n|Susquehanna    |        63,968|  3.14|High Confidence |Safe for algorithmic decisions      |\n|Tioga          |        59,707|  3.23|High Confidence |Safe for algorithmic decisions      |\n|Union          |        64,914|  7.32|Moderate        |Use with caution - monitor outcomes |\n|Venango        |        59,278|  3.45|High Confidence |Safe for algorithmic decisions      |\n|Warren         |        57,925|  5.19|Moderate        |Use with caution - monitor outcomes |\n|Washington     |        74,403|  2.38|High Confidence |Safe for algorithmic decisions      |\n|Wayne          |        59,240|  4.79|High Confidence |Safe for algorithmic decisions      |\n|Westmoreland   |        69,454|  1.99|High Confidence |Safe for algorithmic decisions      |\n|Wyoming        |        67,968|  3.85|High Confidence |Safe for algorithmic decisions      |\n|York           |        79,183|  1.79|High Confidence |Safe for algorithmic decisions      |\n\n\n:::\n:::\n\n\n**Key Recommendations:**\n\n**Your Task:** Use your analysis results to provide specific guidance to the department.\n\n1. **Counties suitable for immediate algorithmic implementation:**\n\nThe following counties are considered \"High Confidence\" and are suitable for algorithmic implementation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhigh_confidence_table <- pa_reliability %>%\n  filter(reliability == \"High Confidence\") %>%\n  select(county_name, median_incomeE, moe_percentage, reliability) %>%\n  arrange(desc(median_incomeE))\n\nkable(\n  high_confidence_table,\n  col.names = c(\"County\", \"Median Income (Estimate)\", \"MOE %\", \"Reliability\"),\n  caption = \"Counties with High-Confidence Median Income Estimates (ACS 2022)\",\n  format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\nTable: Counties with High-Confidence Median Income Estimates (ACS 2022)\n\n|County         | Median Income (Estimate)| MOE %|Reliability     |\n|:--------------|------------------------:|-----:|:---------------|\n|Chester        |                  118,574|  1.70|High Confidence |\n|Bucks          |                  107,826|  1.41|High Confidence |\n|Montgomery     |                  107,441|  1.27|High Confidence |\n|Delaware       |                   86,390|  1.53|High Confidence |\n|Butler         |                   82,932|  2.61|High Confidence |\n|Cumberland     |                   82,849|  2.20|High Confidence |\n|Northampton    |                   82,201|  1.93|High Confidence |\n|Lancaster      |                   81,458|  1.79|High Confidence |\n|Monroe         |                   80,656|  3.17|High Confidence |\n|York           |                   79,183|  1.79|High Confidence |\n|Adams          |                   78,975|  4.22|High Confidence |\n|Pike           |                   76,416|  4.90|High Confidence |\n|Perry          |                   76,103|  3.17|High Confidence |\n|Lehigh         |                   74,973|  2.00|High Confidence |\n|Berks          |                   74,617|  1.60|High Confidence |\n|Washington     |                   74,403|  2.38|High Confidence |\n|Allegheny      |                   72,537|  1.20|High Confidence |\n|Lebanon        |                   72,532|  2.69|High Confidence |\n|Franklin       |                   71,808|  3.00|High Confidence |\n|Dauphin        |                   71,046|  2.27|High Confidence |\n|Centre         |                   70,087|  2.77|High Confidence |\n|Westmoreland   |                   69,454|  1.99|High Confidence |\n|Wyoming        |                   67,968|  3.85|High Confidence |\n|Beaver         |                   67,194|  2.28|High Confidence |\n|Susquehanna    |                   63,968|  3.14|High Confidence |\n|Lackawanna     |                   63,739|  2.58|High Confidence |\n|Schuylkill     |                   63,574|  2.40|High Confidence |\n|Lycoming       |                   63,437|  4.39|High Confidence |\n|Fulton         |                   63,153|  3.65|High Confidence |\n|Juniata        |                   61,915|  4.79|High Confidence |\n|Huntingdon     |                   61,300|  4.72|High Confidence |\n|Armstrong      |                   61,011|  3.61|High Confidence |\n|Luzerne        |                   60,836|  2.35|High Confidence |\n|Bradford       |                   60,650|  3.57|High Confidence |\n|Tioga          |                   59,707|  3.23|High Confidence |\n|Columbia       |                   59,457|  3.76|High Confidence |\n|Erie           |                   59,396|  2.55|High Confidence |\n|Blair          |                   59,386|  3.47|High Confidence |\n|Venango        |                   59,278|  3.45|High Confidence |\n|Wayne          |                   59,240|  4.79|High Confidence |\n|Clinton        |                   59,011|  3.86|High Confidence |\n|Crawford       |                   58,734|  3.91|High Confidence |\n|Clarion        |                   58,690|  4.37|High Confidence |\n|Bedford        |                   58,337|  4.47|High Confidence |\n|Mifflin        |                   58,012|  3.43|High Confidence |\n|McKean         |                   57,861|  4.75|High Confidence |\n|Lawrence       |                   57,585|  3.07|High Confidence |\n|Philadelphia   |                   57,537|  1.38|High Confidence |\n|Somerset       |                   57,357|  2.78|High Confidence |\n|Mercer         |                   57,353|  3.63|High Confidence |\n|Indiana        |                   57,170|  4.65|High Confidence |\n|Clearfield     |                   56,982|  2.79|High Confidence |\n|Jefferson      |                   56,607|  3.41|High Confidence |\n|Potter         |                   56,491|  4.42|High Confidence |\n|Northumberland |                   55,952|  2.67|High Confidence |\n|Fayette        |                   55,579|  4.16|High Confidence |\n|Cambria        |                   54,221|  3.34|High Confidence |\n\n\n:::\n:::\n\n\n\n2. **Counties requiring additional oversight:**\n\nThe following counties are of Moderate confidence. These counties would need closer analysis due to their risk for under representation. Additional data, outreach to local leaders and organizations, and likely additional funding would be key in successful allocation of resources.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoderate_confidence_table <- pa_reliability %>%\n  filter(reliability == \"Moderate\") %>%\n  select(county_name, median_incomeE, moe_percentage, reliability) %>%\n  arrange(desc(median_incomeE))\n\nkable(\n  moderate_confidence_table,\n  col.names = c(\"County\", \"Median Income (Estimate)\", \"MOE %\", \"Reliability\"),\n  caption = \"Counties with Moderate-Confidence Median Income Estimates (ACS 2022)\",\n  format.args = list(big.mark = \",\")\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Counties with Moderate-Confidence Median Income Estimates (ACS 2022)\n\n|County   | Median Income (Estimate)| MOE %|Reliability |\n|:--------|------------------------:|-----:|:-----------|\n|Montour  |                   72,626|  7.09|Moderate    |\n|Greene   |                   66,283|  6.41|Moderate    |\n|Snyder   |                   65,914|  5.56|Moderate    |\n|Union    |                   64,914|  7.32|Moderate    |\n|Carbon   |                   64,538|  5.31|Moderate    |\n|Sullivan |                   62,910|  9.25|Moderate    |\n|Elk      |                   61,672|  6.63|Moderate    |\n|Warren   |                   57,925|  5.19|Moderate    |\n|Forest   |                   46,188|  9.99|Moderate    |\n|Cameron  |                   46,186|  5.64|Moderate    |\n\n\n:::\n:::\n\n\n3. **Counties needing alternative approaches:** The analysis did not find any counties with a low confidence level of data. This does not mean that there is no risk of inaccurate conclusions using algorithmic decision making but does allow for less reliance on alternative approaches.\n\n## Questions for Further Investigation\n\nQuestions that arose during this analysis:\n\n1. What additional data sets would be useful to overcome poor confidence in census data?\n\n2. How can state agencies increase participation in the census and improve accuracy of census record?\n\n3. WHat is the estimated participation in the census and how does it change based on demographics?\n\n# Technical Notes\n\n**Data Sources:** \n- U.S. Census Bureau, American Community Survey 2018-2022 5-Year Estimates\n- Retrieved via tidycensus R package on [date]\n\n**Reproducibility:** \n- All analysis conducted in R version 4.5.1\n- Census API key required for replication\n- Complete code and documentation available at:\n\nhttps://musa-5080-fall-2025.github.io/portfolio-setup-jocajoe/\n\n**Methodology Notes:**\n\nThis analysis was conducted with data from the 2020 U.S. Census and the 2023 5 year ACS data. It focused on Pennsylvania counties and census tracks. Should it be reproduced in the future, updated data should be utilized. \n\n**Limitations:**\nThis analysis was limited by geographic scope and sample size of included counties. It would be prudent to extend this study to all counties in PA at the tract level. It would also be of interest to perform this study with multiple concurrent ACS surveys to ensure understand how these demographics are changing over time.\n\n---\n\n## Submission Checklist\n\nBefore submitting your portfolio link on Canvas:\n\n- [ ] All code chunks run without errors\n- [ ] All \"[Fill this in]\" prompts have been completed\n- [ ] Tables are properly formatted and readable\n- [ ] Executive summary addresses all four required components\n- [ ] Portfolio navigation includes this assignment\n- [ ] Census API key is properly set \n- [ ] Document renders correctly to HTML\n\n**Remember:** Submit your portfolio URL on Canvas, not the file itself. Your assignment should be accessible at `your-portfolio-url/assignments/assignment_1/your_file_name.html`",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}